// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type Products struct {
	ID      int32           `json:"id"`
	Count   sql.NullString  `json:"count"`
	Name    sql.NullString  `json:"name"`
	Price   sql.NullFloat64 `json:"price"`
	Desc    sql.NullString  `json:"desc"`
	Picture sql.NullString  `json:"picture"`
}

type User struct {
	ID        int32          `json:"id"`
	Email     sql.NullString `json:"email"`
	Name      sql.NullString `json:"name"`
	Password  sql.NullString `json:"password"`
	Picture   sql.NullString `json:"picture"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type UserItem struct {
	ID     int32         `json:"id"`
	UserID sql.NullInt32 `json:"user_id"`
	ItemID sql.NullInt32 `json:"item_id"`
	Count  sql.NullInt32 `json:"count"`
}
