// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: products.sql

package db

import (
	"context"
	"database/sql"
)

const addProduct = `-- name: AddProduct :execresult
INSERT INTO user_item (
    user_id,item_id,count
) VALUES (
   ?, ?,?
)
`

type AddProductParams struct {
	UserID sql.NullInt32 `json:"user_id"`
	ItemID sql.NullInt32 `json:"item_id"`
	Count  sql.NullInt32 `json:"count"`
}

func (q *Queries) AddProduct(ctx context.Context, arg AddProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addProduct, arg.UserID, arg.ItemID, arg.Count)
}
