import type { NextPage } from "next";
import Head from "next/head";
import Footer from "./sections/Footer";
import MainContent from "./sections/MainContent";
import Navbar from "./sections/Navbar";
import Sidebar from "./sections/Sidebar";
import { GetStaticProps } from "next";
import { prisma } from "../../lib/prisma";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Sidebar />
      <MainContent />
      <Footer />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const user = await prisma.user.findMany();
  return {
    props: {
      user: JSON.parse(JSON.stringify(user)),
    },
  };
};

export default Home;
