import type { NextPage } from "next";
import Head from "next/head";
import Footer from "./sections/Footer";
import MainContent from "./sections/MainContent";
import Navbar from "./sections/Navbar";
import Sidebar from "./sections/Sidebar";
import { GetServerSideProps, GetStaticProps } from "next";
import { prisma } from "../../lib/prisma";

const Home: NextPage = ({ product }: any) => {
  return (
    <>
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar product={product} />
      <Sidebar />
      <MainContent />
      <Footer />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const product = await prisma.product.findMany();
  return {
    props: { product },
  };
};

export default Home;
