
import Head from "next/head";
import MainContent from "./sections/MainContent";
import Navbar from "./sections/Navbar";
import Sidebar from "./sections/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Sidebar />
      <MainContent />
    </>
  );
}
